import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage } from "~/components/loading";

dayjs.extend(relativeTime);

function Avatar(props: { src: string; author?: string }) {
  return (
    <Image
      className="h-8 w-8 rounded-full"
      src={props.src}
      alt={`${props.author} profile image`}
      height="32"
      width="32"
    />
  );
}

function CreatePostWizard() {
  const { user } = useUser();
  if (!user) return null;

  return (
    <div className="flex gap-3">
      <Avatar src={user.profileImageUrl} author={user.fullName ?? ""} />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
}

type PostWithAuthor = RouterOutputs["posts"]["getAll"][number];
function PostView({ author, ...post }: PostWithAuthor) {
  return (
    <div className="flex items-center gap-3 border-b border-slate-400 p-4">
      <Avatar src={author.profileImageUrl} author={author.firstName ?? ""} />
      <div className="flex flex-col gap-1">
        <div className="flex gap-1 text-slate-200">
          <span>{`${author.firstName}`}</span>
          <span>·</span>
          <span className="font-thin">{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
}

function Feed() {
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <LoadingPage />;

  if (!data) return <div>Something went wrong...</div>;

  return (
    <div className="flex flex-col">
      {data.map((post) => (
        <PostView key={post.id} {...post} />
      ))}
    </div>
  );
}

export default function Home() {
  const { user, isSignedIn, isLoaded } = useUser();

  // start fetching asap
  api.posts.getAll.useQuery();

  if (!isLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Twitter t3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex flex-col gap-4 border-b border-slate-400 p-4">
            <div className="flex items-center justify-between gap-4">
              <h1 className="text-xl font-medium">Twitter t3</h1>
              <span className="font-extralight">Hello {user?.fullName}</span>
            </div>
            {!isSignedIn ? <SignInButton /> : <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}
